### ISSUE TITLE
Backend: rota de login de usuario

### ISSUE THREAD

**Issue by PedroRonzani18** [Codelife-Compet/codelife.dev#113]
### What your feature is related?

Another

### Description

Implementação da rota de login de usuário. 

### Tasks

- [x] Criar controller base na rota http "user/create"

Use Case:
- [x] usecaserequest deve ser uma interface
- [x] usecase response uma iinterface usando Either
- [x] método execute retorna right para sucesso, e left para erro
- [x] método execute faz chamada ao banco de dados
- [x] com isso, implementar os devidos métodos no repositório do banco de dados

Controller:
- [x] validar dados de entrada (github_token ou linkedin_token) via zod
- [x] tratar o retorno do caso de uso com return.isLeft() (significando erro)
- [x] caso sucesso, retornar nome do usuario

Testes:
- [x] Testes unitários usando vitest para sucesso e erro proposital de login
