### ISSUE TITLE
Social and jwt authorization flow

### ISSUE THREAD

**Issue by bidwolf** [Codelife-Compet/codelife.dev#12]
### What your feature is related?

Another

### Description

This issue is needed to create a authorization flow in our application and link them with the permissions that our app needs.

### Tasks

- [ ] Install next-auth to provide social functionality 
- [ ] Create tokens in the development environment 
- [ ] Make authorization flow with jwt using our own backend

### Acceptance Criteria

1. Routes permissions based on authorization 
2. Functionalities based on user permissions 
3. User information is available for many contexts(only not sensible data)

**Comment by bidwolf** [comment]
Utilizar o seguinte comando para desenvolver : 

```bash
git fetch origin
git checkout 12-social-and-jwt-authorization-flow
```

**Comment by bidwolf** [comment]
Existem alguns vídeos no youtube sobre como utilizar o Next-auth para autenticação social.

Quaisquer dúvidas estou a disposição.
