### ISSUE TITLE
 Carousel component

### ISSUE THREAD

**Issue by bidwolf** [Codelife-Compet/codelife.dev#26]
### What your feature is related?

Components

### Description

This feature aims to create an animated Carousel component and improve that functionality to any kind of data.

### Tasks

- [x] Create styles for the next button and previous button
- [x] Users can see what position the current element is on the carousel
- [x] Works in any data
- [x] Use animations on the mount and unmount states 
- [x] #37
- [x] Documentation in Storybook

### Acceptance Criteria

1. First criteria: Use framer-motion to animate
2. Second criteria: Have three variants (primary, secondary, and tertiary)
3. Third criteria: Improve performance in components like that (if necessary).
4. Fourth criteria: Create documentation on the Storybook with a use case

**Comment by ooBraia** [comment]
Bom demaize!
