### ISSUE TITLE
feature-box-challenge-projects

### ISSUE THREAD

**Issue by luizleroy01** [Codelife-Compet/codelife.dev#27]
### What your feature is related?

Components

### Description

Create a box to contains details about projects developed by codelife users like screenshot from project main page, title and a little description

### Tasks

- [ ] Create box Structure 
- [ ] Create an style to the box
- [ ] Create a layout to all boxes in codelife main page
...

### Acceptance Criteria

1. First criteria : be nice
2. Second criteria : be smart
3. Third criteria : be sheap
...

┆Issue is synchronized with this [Trello card](https://trello.com/c/m5vkhcAz) by [Unito](https://www.unito.io)

**Comment by bidwolf** [comment]
@luizleroy01 modifica o acceptance criteria!
