### ISSUE TITLE
Testes automatizados usando Testing library

### ISSUE THREAD

**Issue by bidwolf** [Codelife-Compet/codelife.dev#35]
### What your feature is related?

Tests

### Description

Essa issue pretende tornar possível criar testes automatizados usando Testing library e rodar esses testes dentro do mono repositorio.

### Tasks

- [x] Instalar a biblioteca Testing library
- [x] configurar o arquivo turbo.json para que seja possivel rodar todos os testes existentes de uma vez (baseado no que mudou)
- [x] Criar um teste de exemplo
- [x] Documentar um tutorial de como criar um teste relacionado ao seu componente react
- [x] Configurar diferentes workspaces de testes para cada pacote

┆Issue is synchronized with this [Trello card](https://trello.com/c/cKJbuN6e) by [Unito](https://www.unito.io)
