### ISSUE TITLE
Modal

### ISSUE THREAD

**Issue by bidwolf** [Codelife-Compet/codelife.dev#64]
### What your feature is related?

Components

### Description

A modal component with animation with ***framer-motion*** to use a dialog/modal logic.

### Tasks

- [ ] Create the component with styles on @codelife-ui
- [ ] Create the hook to use the modal logic
- [ ] Documents the component on storybook
- [ ] Create tests for the modal logic and component

### Acceptance Criteria

1. The backdrop has to blur the background
2. The modal starts closed
3. The trigger element can be anything
4. The content must appear from the bottom to the center
5. Must to be a close modal button
6. Must to be closed when the user click outside the content
