### ISSUE TITLE
Página de política de privacidade

### ISSUE THREAD

**Issue by bidwolf** [Codelife-Compet/codelife.dev#96]
### What your feature is related?

Components

### Description

A página de política de privacidade contribui para que o usuário saiba quais informações são utilizadas pela nossa aplicação.
O modelo utilizado será o mesmo do site oficial.

### Tasks

- [ ] Criar a página de política de privacidade
- [ ] Utilizar o I18n para tradução da página
- [ ] Atualizar o footer da página para redirecionar para  a página em questão

### Acceptance Criteria

1. First criteria : A página deve ser pública 
2. Second criteria : Deve possuir tradução
3. Third criteria : Seguir o modelo de estilizações utilizando a lib codelife-ui (quaisquer adições na biblioteca em relação a componentes atômicos são bem vindos)

**Comment by bidwolf** [comment]
Para utilizar as traduções dentro da página observem a pasta `public/locales` e o repositório original https://github.com/Codelife-Compet/codelife/pulls que contém o conteúdo da página em si!
